In [2]:
#pip install numpy
#conda install numpy
import numpy as np

In [6]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [16]:
np.zeros(5)
np.zeros([5,5])
np.zeros((5,5))
np.zeros((2,3,4))
np.zeros((2,3,4,1,2))
np.zeros((1000,200))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.arange(1,20) #[1,20[

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [27]:
np.arange(-12,1) #[12,1[

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [28]:
np.arange(0,20,2) #Del [0-20[ en intervalos de 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np.arange(0,2.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(20).reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [34]:
len(np.ones(12))

12

In [35]:
len(np.ones(12).reshape(4,3))

4

In [36]:
np.ones(12).reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.zeros(20).reshape(2,5,2).reshape(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [40]:
np.ones(12).reshape(4,3).shape

(4, 3)

In [42]:
np.array([1,7,12,16]).reshape(2,2)

array([[ 1,  7],
       [12, 16]])

In [43]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [44]:
a

array([10, 10, 10])

In [45]:
b

array([5, 5, 5])

In [46]:
a+b

array([15, 15, 15])

In [47]:
a-b

array([5, 5, 5])

In [48]:
a+5

array([15, 15, 15])

In [50]:
a-8

array([2, 2, 2])

In [51]:
a*b

array([50, 50, 50])

In [52]:
a*3

array([30, 30, 30])

In [53]:
a/b


array([2., 2., 2.])

In [55]:
a/2

array([5., 5., 5.])

In [57]:
a % b

array([0, 0, 0], dtype=int32)

In [58]:
a % 3

array([1, 1, 1], dtype=int32)

In [59]:
muestra = np.arange(20).reshape(5,2,2)

In [60]:
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [150]:
###Forma del Inge
mayores_cinco = muestra > 5
menores_catorce = muestra < 14
pares = muestra % 2==0 
respuesta = mayores_cinco & menores_catorce & pares

In [146]:
muestra[respuesta]

array([ 6,  8, 10, 12])

In [149]:
muestra[(muestra>5) & (muestra<14) & (muestra%2 == 0)]

array([ 6,  8, 10, 12])

In [152]:
#### Como le hice
muestra1 = muestra > 5
muestra2 = muestra < 14

In [156]:
muestra[muestra1 & muestra2]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [157]:
muestra3 = muestra %2 ==0

In [1]:
muestra[muestra1 & muestra2 & muestra3]

NameError: name 'muestra' is not defined

In [6]:
A=np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [8]:
B=np.arange(4,8).reshape(2,2)
B

array([[4, 5],
       [6, 7]])

In [9]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [10]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [11]:
np.dot(B,A)

array([[10, 19],
       [14, 27]])

In [12]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
arreglo_doce.sum()

66

In [14]:
arreglo_doce.min()

0

In [15]:
arreglo_doce.max()

11

In [16]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [19]:
arreglo_doce.reshape(3,2,2).sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [20]:
arreglo_doce.reshape(3,2,2).sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [21]:
arreglo_doce.reshape(3,2,2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])