In [3]:
import numpy as np

In [5]:
arreglo_grados = np.array([0,30,45,60,90])

In [7]:
arreglo_radianes = arreglo_grados*np.pi/180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [8]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [9]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [10]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [14]:
numero_random = np.random.randint(11)
numero_random

9

In [19]:
numero_random_negativo = np.random.randint(-9,2)
numero_random_negativo

-8

In [21]:
arreglo_random = np.random.randint(10,20,8)
arreglo_random

array([12, 14, 10, 19, 11, 15, 17, 17])

In [22]:
np.random.rand(9)

array([0.18906551, 0.34292037, 0.25910878, 0.04715843, 0.70178484,
       0.90183152, 0.61436733, 0.07306432, 0.70935571])

In [27]:
np.random.rand(3,2)

array([[0.35357967, 0.38860292],
       [0.5885564 , 0.25607652],
       [0.59432286, 0.92339354]])

In [29]:
np.average(arreglo_random)

14.375

In [30]:
np.mean(arreglo_random)

14.375

In [32]:
np.median(arreglo_random)

14.5

In [31]:
np.std(arreglo_random)

2.9973947020704497

In [33]:
np.var(arreglo_random)

8.984375

In [34]:
arreglo_random.mean()

14.375